version: "2"
run:
  modules-download-mode: readonly
  timeout: 2m
  concurrency: 4
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - deferInLoop
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 20
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - lll
          - mnd
        path: _test\.go
      - linters:
          - all
        path: testdata/
      - linters:
          - gochecknoinits
        path: main\.go
      - linters:
          - gosec
        path: (internal/parser|internal/config)/.*\.go
        text: G304
      - linters:
          - mnd
        text: (0600|0750|0755|0644|0400)
      - linters:
          - mnd
        text: 'Magic number: (2|20)'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hacomono-lib/go-i18ngen
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
