services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
    command: bash

  # Service for running tests in isolated environment
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    command: make test

  # Service for running linter
  lint:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
    working_dir: /workspace
    command: make lint

volumes:
  go-mod-cache:
  go-build-cache: 