services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/workspace
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    working_dir: /workspace
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    command: bash
    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
  go-build-cache: 